name: spark

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  repository_dispatch:
    types: [spark]

jobs:
  spark:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
    
    - name: Set up Spark
      uses: vemonet/setup-spark@v1
      with:
        spark-version: "3.5.3"

    - name: Verify Spark Installation
      run: spark-shell --version
